# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalAdaptive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uiid', models.CharField(max_length=500)),
                ('pay_key', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Orders')),
            ],
        ),
    ]
