# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='shopify_domain',
            new_name='shop_domain',
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='password',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
