# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-15 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchantshopecredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantshopecredentials',
            name='request_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='merchantshopecredentials',
            name='request_token_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
