# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_auto_20171116_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='token_time',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
