# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0007_auto_20171117_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='token_time',
        ),
    ]
