# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0008_remove_accountdetail_token_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='token_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
