# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('paypal_emailid', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('password', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('activation_key', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('token', models.CharField(blank=True, max_length=500)),
                ('platform', models.CharField(default='Shopify', max_length=100)),
                ('added_shop', models.CharField(default='no', max_length=100)),
                ('is_app_uninstall', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.AccountType')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('selling_price', models.FloatField(default=0.0)),
                ('dropshipping_price', models.FloatField(default=0.0)),
                ('dropshipping_percentage', models.FloatField(default=0.0)),
                ('wholesale_price', models.FloatField(default=0.0)),
                ('wholesale_percentage', models.FloatField(default=0.0)),
                ('is_tax', models.BooleanField(default=False)),
                ('sku', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('isAdded', models.BooleanField(default=False)),
                ('quantity', models.BigIntegerField(default=5)),
                ('PlatformProductId', models.BigIntegerField(default=0)),
                ('platform', models.CharField(default='Shopify', max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('weight_unit', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopify.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.AccountType'),
        ),
    ]
