# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ok',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
