# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_account_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ok',
        ),
        migrations.AddField(
            model_name='account',
            name='token_time',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
    ]
