# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_auto_20171205_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=100)),
                ('platform_key', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
