# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-11 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_apiauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varients',
            old_name='name',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='varients',
            old_name='varient_prop',
            new_name='size',
        ),
    ]
