# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-11 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0006_auto_20171211_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarients',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvarients',
            name='varients',
        ),
        migrations.AddField(
            model_name='products',
            name='isconfig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='parent_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='varient_level',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='varient_value',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductVarients',
        ),
        migrations.DeleteModel(
            name='Varients',
        ),
    ]
