# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 13:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopify', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.FloatField(default=0.0)),
                ('ShopifyProductId', models.BigIntegerField()),
                ('ProductQty', models.BigIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('fulfillment_status', models.TextField(blank=True, max_length=100, null=True)),
                ('fulfillment_quantity', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('OrderId', models.BigIntegerField()),
                ('paymentMethod', models.CharField(max_length=200)),
                ('financial_status', models.CharField(max_length=100)),
                ('OrderUrl', models.CharField(blank=True, max_length=1000, null=True)),
                ('total_amount', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('fulfillment_status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_province', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_country', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_status', models.CharField(blank=True, max_length=100)),
                ('vendorPlateformOrderId', models.CharField(blank=True, max_length=200)),
                ('paid_by_merchant', models.CharField(blank=True, max_length=100)),
                ('vendor_order_number', models.CharField(blank=True, max_length=100)),
                ('tracking_company', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('tracking_number', models.BigIntegerField(blank=True, null=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.AccountDetail')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopify.Account')),
            ],
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Orders'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Account'),
        ),
    ]
